services:
  - docker

env:
  global:
    - DOCKER_ORG=koinos
    - DOCKER_REPO=koinos-telegram-bot
    - TAG=`if [ ${TRAVIS_BRANCH} == "main" ]; then echo -n latest; else echo -n ${TRAVIS_BRANCH}; fi`

script:
  - docker build . -t ${DOCKER_ORG}/${DOCKER_REPO}:${TAG}

after_success:
  - echo "${DOCKER_PASSWORD}" | docker login -u ${DOCKER_USERNAME} --password-stdin
  - docker push ${DOCKER_ORG}/${DOCKER_REPO}:${TAG}
